# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20211220_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=4000),
        ),
    ]
