# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-25 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_auto_20211220_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(),
        ),
    ]
