# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0013_auto_20220308_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mob',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
